Bookish.Web/Models/AddBookFormData.cs
namespace Bookish.Web.Models {
    public class AddBookFormModel {
        public string Isbn { get; set; }
        public string Title { get; set; }
        public string Author { get; set; }
        public string NumCopiesOwned { get; set; }
    }
}

Bookish.Web/Models/BookExceptionList.cs
using System;
using System.Collections.Generic;

namespace Bookish.Web.Models {
    public class BookExceptionList {
        public IEnumerable<Exception> Exceptions { get; set; }
        
        public BookExceptionList(IEnumerable<Exception> exceptions) {
            Exceptions = exceptions;
        }
    }
}

Bookish.Web/Models/BookForWeb.cs
using System.Collections.Generic;
using System.Linq;
using Bookish.DataAccess.Models;

namespace Bookish.Web.Models {
    public class BookForWeb {
        public string Isbn { get; set; }
        public string Title { get; set; }
        public string Author { get; set; }
        public int NumCopiesOwned { get; set; }
        public int NumCopiesAvailable { get; set; }

        public BookForWeb(string isbn, string title, string author, int numCopiesOwned, int numCopiesAvailable) {
            Isbn = isbn;
            Title = title;
            Author = author;
            NumCopiesOwned = numCopiesOwned;
            NumCopiesAvailable = numCopiesAvailable;
        }

        public static IEnumerable<BookForWeb> GenerateWebBookEnumerableFromDBRecords(
            IEnumerable<BookFromDB> books,
            IEnumerable<LoanFromDB> loans
        ) {
            return books.GroupBy(book => book.Isbn)
                .Select(bookGrouping => {
                    BookFromDB firstBookInGrouping = bookGrouping.First();
                    return new BookForWeb(
                        firstBookInGrouping.Isbn,
                        firstBookInGrouping.Title,
                        firstBookInGrouping.Author,
                        bookGrouping.Count(),
                        bookGrouping.Count(book => book.IsAvailable(loans))
                    );
                });
        }
    }
}

Bookish.Web/Models/BookListModel.cs
using System.Collections.Generic;

namespace Bookish.Web.Models {
    public class BookListModel {
        public IEnumerable<BookForWeb> BooksList { get; set; }

        public BookListModel(IEnumerable<BookForWeb> booksList) {
            BooksList = booksList;
        }
    }
}

Bookish.Web/Models/BooksPageModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using Bookish.DataAccess;
using Bookish.DataAccess.Models;
using Microsoft.AspNetCore.Mvc;

namespace Bookish.Web.Models {
    public class BooksPageModel {
        public BookListModel BookList { get; set; }
        public AddBookFormModel FormModel { get; set; }
        public BookExceptionList ExceptionList { get; set; }

        public BooksPageModel(IEnumerable<BookFromDB> bookList, IEnumerable<LoanFromDB> loanList,
            IEnumerable<Exception> exceptions) {
            BookList = new BookListModel(
                GenerateWebBookEnumerableFromDBRecords(bookList, loanList));

            ExceptionList = new BookExceptionList(exceptions);
        }

        private static IEnumerable<BookForWeb> GenerateWebBookEnumerableFromDBRecords(
            IEnumerable<BookFromDB> books,
            IEnumerable<LoanFromDB> loans
        ) {
            return books.GroupBy(book => book.Isbn)
                .Select(bookGrouping => {
                    BookFromDB firstBookInGrouping = bookGrouping.First();
                    return new BookForWeb(
                        firstBookInGrouping.Isbn,
                        firstBookInGrouping.Title,
                        firstBookInGrouping.Author,
                        bookGrouping.Count(),
                        bookGrouping.Count(book => book.IsAvailable(loans))
                    );
                });
        }
    }
}

Bookish.Web/Models/ErrorViewModel.cs
using System;

namespace Bookish.Web.Models {
    public class ErrorViewModel {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Bookish.Web/Controllers/DataController.cs
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Net;
using System.Threading.Tasks;
using Bookish.DataAccess;
using Bookish.DataAccess.Models;
using Bookish.Web.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace Bookish.Web.Controllers {
    public class DataController : Controller {
        private readonly ILogger<DataController> _logger;
        private readonly DatabaseAccessObject _dao;

        public DataController(ILogger<DataController> logger) {
            _logger = logger;
            _dao = new DatabaseAccessObject();
        }

        [HttpPost]
        public IActionResult AddBook(AddBookFormModel bookData) {
            Console.WriteLine(
                $"Trying to add book: {bookData.Isbn} | {bookData.Title} | {bookData.Author} | {bookData.NumCopiesOwned}");

            List<Exception> exceptions = new List<Exception>();
            try {
                int numCopies = GetNumCopies(bookData.NumCopiesOwned);
                for (int bookNumber = 0; bookNumber < numCopies; bookNumber++) {
                    _dao.Add(new BookForDB(bookData.Isbn, bookData.Title, bookData.Author));
                }
            } catch (Exception e) {
                exceptions.Add(
                    new Exception(
                        "There was a problem adding the new book to the database: " + e.Message
                    )
                );
            }

            return View("Books", GenerateBooksPageModel(exceptions));
        }

        public IActionResult Books() {
            return View(GenerateBooksPageModel(new List<Exception>()));
        }
        
        private int GetNumCopies(string numCopiesOwned) {
            try {
                return int.Parse(numCopiesOwned);
            } catch (FormatException) {
                throw new Exception("NumCopiesOwned is in the wrong format.");
            } catch (ArgumentNullException) {
                throw new Exception("NumCopiesOwned was not given.");
            } catch (OverflowException) {
                throw new Exception("NumCopiesOwned is too big / small to fit into an int.");
            }
        }
        
        private BooksPageModel GenerateBooksPageModel(List<Exception>  exceptions) {
            List<LoanFromDB> loans = new List<LoanFromDB>();
            List<BookFromDB> books = new List<BookFromDB>();
            try {
                books.AddRange(_dao.GetAllBooks());
                loans.AddRange(_dao.GetAllLoans());
            } catch (Exception e) {
                exceptions.Add(e);
            }
            
            return new BooksPageModel(books, loans, exceptions);
        }
    }
}

Bookish.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Bookish.DataAccess;
using Bookish.DataAccess.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Bookish.Web.Models;

namespace Bookish.Web.Controllers {
    public class HomeController : Controller {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger) {
            _logger = logger;
        }

        public IActionResult Index() {
            return View();
        }

        public IActionResult Privacy() {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error() {
            return View(new ErrorViewModel {RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier});
        }
    }
}

Bookish.Web/Views/Data/AddBookPartial.cshtml
@using Microsoft.EntityFrameworkCore;
@model AddBookFormModel;

@using (@Html.BeginForm("AddBook", "Data")) {
    <tr>
        <td>
            @Html.TextBoxFor(model => model.Isbn)
        </td>
        <td>
            @Html.TextBoxFor(model => model.Title)
        </td>
        <td>
            @Html.TextBoxFor(model => model.Author)
        </td>
        <td>
            @Html.TextBoxFor(model => model.NumCopiesOwned)
        </td>
        <td>
            <input type="submit" class="btn" value="Add">
        </td>
    </tr>
}

Bookish.Web/Views/Data/BookListPartial.cshtml
@model BookListModel;

@foreach (BookForWeb book in Model.BooksList) {
    <tr>
        <th scope="row">@book.Isbn</th>
        <td>@book.Title</td>
        <td>@book.Author</td>
        <td>@book.NumCopiesOwned</td>
        <td>@book.NumCopiesAvailable</td>
    </tr>
}

Bookish.Web/Views/Data/Books.cshtml
@using Microsoft.EntityFrameworkCore
@model BooksPageModel;

@{
    ViewData["title"] = "Books Page";
}

<div>
    @if (Model.ExceptionList.Exceptions.Any()) {
        @foreach (Exception exception in Model.ExceptionList.Exceptions) {
            <div class="alert alert-danger">
                An error has occurred: @exception.Message
            </div>
        }
    }
    <h1>This is a list of the books currently owned by the library</h1>
    <table class="table table-bordered">
        <thead>
        <tr>
            <th scope="col">ISBN</th>
            <th scope="col">Title</th>
            <th scope="col">Author</th>
            <th scope="col">Number of Copies Owned</th>
            <th scope="col">Number of Copies Available</th>
        </tr>
        </thead>
        <tbody>
        <partial name="AddBookPartial" model="@Model.FormModel"/>
        <partial name="BookListPartial" model="@Model.BookList"/>
        </tbody>
    </table>
</div>

Bookish.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Bookish.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Bookish.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Bookish.Web</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li>
                            <a class="nav-link text-dark" asp-area="" asp-controller="Data" asp-action="Books">Books</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - Bookish.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>